### ISSUE TITLE
Config to take out welcome message

### ISSUE THREAD

**Issue by Electricpantz** [Sebastrn/AppliedCooking#11]
Would it be possible for you to include a config file, so that we can toggle off the welcome message when loading into a new world? I am helping someone build a mudpack, and this would help us a lot with keeping immersion in the pack

**Comment by smolinacadena** [comment]
Hi @Electricpantz 

I have set up two types of config files. One for the client called sebastrnlib-client.toml and one for a server called sebastrnlib-server.toml.

You should be able to control the message there.

**Comment by Sebastrn** [comment]
Hi @Electricpantz 

I have set up two different configs files for that called sebastrnlib-client.toml and sebastrnlib-server.toml.

Let me know if that works.

**Comment by Electricpantz** [comment]
Looks like that did work, Thank you!
