### ISSUE TITLE
Config Request for AE and RS

### ISSUE THREAD

**Issue by whatthedrunk** [Sebastrn/AppliedCooking#5]
Can you add a way to remove the chat message when starting a new world?
![image](https://github.com/Sebastrn/AppliedCooking/assets/8105116/4f3573fd-f6d1-496d-a54f-d448b1607509)

**Comment by Sebastrn** [comment]
Hi @whatthedrunk 

As you can see in your screenshot, the message comes from my core mod called SebastrnLib. That mod already has client and server configs for the exact feature you're requesting. Please check it out and let me know if you have any issues.

I'll close this one for now.
